<?php

namespace FG\PetManagerBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
	
public function getLikeQueryBuilder($pattern){

		return $this
		->createQueryBuilder('c')
		->where('c.type LIKE :pattern')
		->setParameter('pattern', $pattern)
		;
	}
}