<?php

namespace FG\PetManagerBundle\Repository;

/**
 * MascotteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MascotteRepository extends \Doctrine\ORM\EntityRepository
{

}
