<?php

namespace FG\PetManagerBundle\Repository;

/**
 * MascotteCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MascotteCatRepository extends \Doctrine\ORM\EntityRepository
{


}